### ISSUE TITLE
Ditching Sizzle

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#110]
Sizzle is a good selector engine, but it slows us down and does not let us implement some crucial features.

In order to solve this, we should implement our own selector engine.

Useful link: https://www.w3.org/TR/selectors-4/#context

TBD: explain how it should work

* * *

this issues should be fixes while replacing Sizzle:
- [x] Rules with insensitive attribute don't work https://github.com/AdguardTeam/ExtendedCss/issues/104
- [x] Some :xpath rules don't work https://github.com/AdguardTeam/ExtendedCss/issues/106
- [x] Remake :upward() after Sizzle replacement https://github.com/AdguardTeam/ExtendedCss/issues/111
- [x] https://github.com/AdguardTeam/ExtendedCss/issues/141
- [x] Can not hide element with 'xlink:href' https://github.com/AdguardTeam/ExtendedCss/issues/99
- [x] Improve performance for cases like this: https://github.com/AdguardTeam/ExtendedCss/issues/136

**Comment by slavaleleka** [comment]
### Can not hide element with 'xlink:href' https://github.com/adguardteam/extendedcss/issues/99:
#### Steps to reproduce:
1. Add this rule:
`mdn.mozillademos.org#?#a[*|href="https://developer.mozilla.org/"]`
2. Go here - https://mdn.mozillademos.org/en-US/docs/Web/SVG/Attribute/xlink:href$samples/topExample

#### Expected behavior

Link should be hidden.

#### Actual behavior

Rule doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/73480599-77134e80-439a-11ea-90a1-47ff14a6f47d.png)

</details>

<hr>

This rule works fine:
`mdn.mozillademos.org##a[*|href="https://developer.mozilla.org/"]`
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/73480883-ff91ef00-439a-11ea-8e53-8777617796e9.png)

</details>

* * *

### Reason
Sizzle does not support Namespaces (and [does not planning to fix it](https://github.com/jquery/sizzle/issues/69#issuecomment-3620438))

**Comment by DandelionSprout** [comment]
Presuming this is the correct thread to track the lack of support for `i` tags in `[class*="example" i]`:

There are currently 33 entries in *Dandelion Sprout's Annoyances List* that are impacted by it, most of whom would not be feasibly possible to convert back to non-`i`:
```
##div[class*=smart-banner i]:not(.smart-banner-visible)
##div[class*=smartbanner i]
##div[id*=smart-banner i]
##div[id*=smartbanner i]
##[class*=facebookShare i]:not(html, body)
##[class*=socialshare i]:not(html, body)
##a[class=facebook i][title="Share this"]
##a[class^=socialbutton i][onclick*="window.open"]
##a[data-share$=Facebook i]
##a[title="Share on Baidu" i]
##a[title="Share on Facebook" i]
##a[title="Share on LinkedIn" i]
##a[title="Share on Pinterest" i]
##a[title="Share on Reddit" i]
##a[title="Share on Telegram" i]
##a[title="Share on Tumblr" i]
##a[title="Share on Twitter" i]
##a[title="Share on VKontakte" i]
##a[title="Share on WhatsApp" i]
##button[class*=ShareOverlayButton i]
##button[class*=SharesButton i]
##button[data-arctrac*=socialShare i]
##div[class*=FooterShare i]
##div[class=instagram-Share i]
##div[class=instagram_Share i]
##div[class=instagramShare i]
##div[class=twitterShare i]
##div[class^=fbshare i]
##div[id^=btnShare i]
~kjokkenskriveren.no##[class*=ShareButton i]:not(button, body, html)
~mewe.com,~www.nrk.no##[class*=share-button i]:not(body, html)
~twitter.com##a[class=twitter i][title=Tweet]
```

**Comment by AdamWr** [comment]
This issue is only about Extended CSS selectors - https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-selectors
Mentioned rules should work fine.

**Comment by DandelionSprout** [comment]
Ah, okay. That explains it.

**Comment by krystian3w** [comment]
I see strange errors:

```adb
! Error: Invalid selector: 'html:not([class*="scrollblock"]) .cdk-overlay-container' -- Selection by :not() pseudo-class is not possible in rule:
psd2-pdev.bskadzidlo.pl,rentis.pl##html:not([class*="scrollblock"]) .cdk-overlay-container
! Error: Invalid selector: 'html:not([style*="overflow"]) #cadre_alert_cookies' -- Selection by :not() pseudo-class is not possible in rule:
pl##html:not([style*="overflow"]) #cadre_alert_cookies
```

both are vanilla CSS works in Firefox 108:

https://jsbin.com/yunaqum/edit?html,css,output
https://jsbin.com/cikatob/edit?html,css,output

**Comment by slavaleleka** [comment]
> Due to the way how `:not()` pseudo-class is implemented in v2.0, it is impossible to apply it to the top DOM node which is `html`, i.e. `#?#html:not(...)` will not work.

https://github.com/AdguardTeam/ExtendedCss/#extended-css-not-limitations

we are going to improve it a bit so `:not()` without extended selectors in arg will be considered as standard, so there will be no limitation about the top DOM node

**Comment by slavaleleka** [comment]
and @krystian3w do not hesitate to create a new issue for any new problem you faced. it would be easier to track discovered problems either for us or other users

**Comment by krystian3w** [comment]
I am terrified of generating an individual issue by pasting it into the wrong repository, as a result of which you have to start zenhub.

If I remember, maybe I'll look at the documentation with future troubles.
